import axios from 'axios';

// Read at runtime from window.APP_CONFIG (config.js, generated by the container's
// entrypoint from real env vars at startup) -- not a Vite build-time env var. This
// is what makes one built image deployable against different backends (dev/staging/
// prod) without a rebuild, which a build-time VITE_* value can't do.
export const API_URL = window.APP_CONFIG.API_URL;

const api = axios.create({
  baseURL: API_URL
});

api.interceptors.request.use(config => {
  const token = localStorage.getItem('token');
  if (token) config.headers.Authorization = `Bearer ${token}`;
  return config;
});

export default api;
